ROBUST_ZSCORE_FLAG_PERCENTILE = 99.7
ROLLING_VARIANCE_WINDOW_HOURS = 6
ROLLING_VARIANCE_FLAG_THRESHOLD = 1e-6
ISOLATION_FOREST_CONTAMINATION = 0.003
COVERAGE_FLOOR_HOURS = 1500

CHANNEL_BASELINE_WINDOWS = {
    "pressure_max_hpa": 30 * 24,
    "pressure_min_hpa": 30 * 24,
    "precip_total_mm": 14 * 24,
    "precip_rate_mmh": 14 * 24,
}

CHANNELS_REQUIRING_CIRCULAR_TRANSFORM = ["winddir_avg_deg"]
CHANNELS_REQUIRING_LOG_TRANSFORM = ["precip_total_mm", "precip_rate_mmh"]
CHANNELS_EXCLUDED_FROM_STATISTICAL_LAYER = []
